version: '3'

services:

  test_web_service:
    container_name: test_web_service_1
    env_file:
      - .launch/tests/.tests_env
    build:
        context: ./
        dockerfile: .launch/tests/api/Dockerfile
    command: >
      bash -c "sleep 5 && alembic upgrade head && pytest --cov=. tests/"
    volumes:
      - ./:/app
    expose:
      - 8191
    depends_on:
      - test_psql_service

  test_psql_service:
    container_name: test_psql_service_1
    image: postgres:13.5
    env_file:
      - .launch/tests/.tests_env
